[project]
name = 'Quantum-Realm-Exploration-Coordination--QREC-'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.quantum-cartography]
path = 'contracts/quantum-cartography.clar'
clarity_version = 2
epoch = 2.5

[contracts.quantum-expedition-planning]
path = 'contracts/quantum-expedition-planning.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
